#!/bin/bash

# Read data from data.json using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[].type.name' data.json | awk '{printf "%s, ", toupper(substr($0,1,1)) substr($0,2)}' | sed 's/, $//')
formatted_weight=$(jq -r '.weight' data.json | awk '{printf "%.1f", $1 / 10}')
formatted_height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1 / 10}')

# Output in required format
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."